version: "4.0"

services:
  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - auth-service
      - user-service
    networks:
      - internal

  auth-service:
    build: ./services/auth-service
    environment:
      - PORT=3001
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - internal

  user-service:
    build: ./services/user-service
    environment:
      - PORT=3002
    networks:
      - internal

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - internal
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  internal:
    driver: bridge
