version: '1.0'
services:
  auth-service:
    build: services/auth-service
    ports:
      - "3000:3000"
    environment:
      - PORT=3000

  user-service:
    build: services/user-service
    ports:
      - "3001:3000"
    environment:
      - PORT=3000

  gateway:
    build: gateway
    ports:
      - "8081:3000"
    environment:
      - PORT=3000
